version: '3'

services:
  elasticsearch:
    image: elasticsearch:6.5.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  kibana:
    image: kibana:6.5.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mongo:
    image: mongo:latest
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs"]
    ports:
      - "27017:27017"
  mongo-config:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    environment:
      - RS=rs
      - MONGO=mongo
      # - USER=machine
      # - PWD=abc123456
    entrypoint: ['/scripts/setup.sh']


  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"

  monstache:
    build: monstache
    # volumes:
    #   - ./monstache/config.toml:/usr/share/monstache/config.toml
    environment: 
      MONSTACHE_MONGO_URL: "mongodb://mongo:27017"
      MONSTACHE_ES_URLS: "http://elasticsearch:9200"
